### ISSUE TITLE
Link does not exist anymore. 

### ISSUE THREAD

**Issue by cblte** [simonfrey/mastodon_wordpress_autopost#17]
https://github.com/simonfrey/mastodon_wordpress_autopost/blob/c5285bc66e26830857d86b1f00e3d5227dd6d1f4/autopost-to-mastodon/trunk/settings_page.php#L115

The link to the "donate.php" does not exist anymore.

**Comment by simonfrey** [comment]
Thanks for that info.

There is a new one in the 3.0 Version!
