### ISSUE TITLE
Permissions seem a bit excessive

### ISSUE THREAD

**Issue by edent** [simonfrey/mastodon_wordpress_autopost#18]
When I authenticated, Mastodon said

> It will be able to read all your account's data and modify all your account's data

Surely the only permission it needs is `write:statuses`?  Why does it have all the higher level permissions set?

**Comment by simonfrey** [comment]
Hey edent,

especially the new version (3.0) needs more permissions to also show your image and stuff.

Where do you have the info with write:statuses from ? I only see write, read in the api documentation.

Would love to make the permission set more defined, but always thought I have to request complete read and write?

**Comment by abrain** [comment]
The fine-grained permissions were introduced with [Mastodon v2.4.3](https://github.com/tootsuite/mastodon/releases/tag/v2.4.3), and they are now listed in the [API documentation](https://github.com/tootsuite/documentation/blob/master/Using-the-API/OAuth-details.md).

Although the instance I'm on runs version 2.4.4, I was not able to modify the OAuth request to contain one of the new scopes like `scope=read+write%3Astatuses`. The server responds with `The requested scope is invalid, unknown, or malformed. `. Maybe this also has to be adapted when registering the application:
https://github.com/simonfrey/mastodon_wordpress_autopost/blob/70fabad14730f6cdc6bc57527c74807c25253d94/autopost-to-mastodon/trunk/client.php#L18

**Comment by edent** [comment]
Here's a full list of permissions I can see on the most recent release. 

![screenshot_20180831-193446__01](https://user-images.githubusercontent.com/837136/44945639-9abd1880-ade5-11e8-959f-f242f9d5f558.jpg)

**Comment by simonfrey** [comment]
I would love if @edent you could work on a pull request regarding this issue. Currently I don't have the time for it and it is not a mission critical change (as the plugin works with the extensive permissions)

Thanks for your help!

p.S. Where is the screenshot from ?

**Comment by edent** [comment]
That screenshot is from https://botsin.space - I think it is the same for any Mastodon instance.

**Comment by simonfrey** [comment]
I played around with the scopes but also on my instance chaos.social it does never work. Will close this as wont fix. 

If there is a working fix in the future, please consider a pull request.

Thanks for your help!
