### ISSUE TITLE
Shortcode embeds are in the toot

### ISSUE THREAD

**Issue by TimeDoctor** [simonfrey/mastodon_wordpress_autopost#21]
EG: https://mastodon.social/@nuclearmonster/100869243048377113

You can embed a youtube video (or many other things) in a wordpress post by using the [embed][/embed] shortcodes, the autotooter appears to just be dropping them into the post.

**Comment by simonfrey** [comment]
Should be fixed with 3.2.1. Please check if the issue is also fixed for you

Thanks for your help!

**Comment by TimeDoctor** [comment]
works!  https://mastodon.social/@nuclearmonster/100961419086199689 thank you :)
