### ISSUE TITLE
Url on toot includes %postname% instead of the full slug, leading to a 404

### ISSUE THREAD

**Issue by TimeDoctor** [simonfrey/mastodon_wordpress_autopost#25]
eg https://mastodon.social/@nuclearmonster/100962013433947171
and https://mastodon.social/@nuclearmonster/100961419086199689

please let me know if you need any more information in debugging this or if I just need to change a setting.

Thank you 💙

**Comment by simonfrey** [comment]
Is your wordpress setup correctly? 
It could be that this bug has to do with your permalink settings.

The plugin itself get's the permalink from wordpress via https://developer.wordpress.org/reference/functions/get_permalink/ So we do not work at all on that link.

If the link would not be included at all, it could be a bug of the plugin, but I think with this it is likely to be a setup bug in your wordpress.

**Comment by TimeDoctor** [comment]
This problem actually went away with an update to this plugin 👍
