### ISSUE TITLE
Options page capability

### ISSUE THREAD

**Issue by controesempio** [simonfrey/mastodon_wordpress_autopost#32]
Currently the plugin adds an option page which can by accessed only by users with the ``install_plugins`` capability. In a situation where Wordpress is configured not to allow anyone to install plugins (i.e. the deployment of the instance is managed via git instead than using the Wordpress Install/Update mechanism), this makes the plugin unusable.

https://github.com/simonfrey/mastodon_wordpress_autopost/blob/48566285a2a042b1378f2f3e874f24f844e9d314/autopost-to-mastodon/trunk/mastodon_autopost.php#L140-L146

It seems to me that there is no good reason for which the user accessing the option page in order to set up their Mastodon autopost should be able to install plugins (after all, the plugin has already been installed at this point), and that the correct capability should be set to ``manage_options``.

**Comment by simonfrey** [comment]
Thank you for you feedback!
Changed with 3.2.6

**Comment by opensamba** [comment]
Hi, 
we have issue again with this code.
Did you reverted the change?

**Comment by simonfrey** [comment]
@opensamba No clue how that sneaked in again. Will be `manage_options` with 3.2.8

**Comment by opensamba** [comment]
Hi, issue is is still there in version 3.3.2
In case of wordpress multisites, users have no management over the mastodon-autopost plugin if `install_plugins` is enabled,  

I pushed a PR to change to `manage_options` https://github.com/simonfrey/mastodon_wordpress_autopost/pull/40 in order to fix that
