### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by abrain** [simonfrey/mastodon_wordpress_autopost#34]
In the current release (Version 3.2.6) the image files for PayPal and Patreon are missing.

![bildschirmfoto 2019-01-20 um 11 43 36](https://user-images.githubusercontent.com/1263052/51438175-c82d3480-1ca8-11e9-8f67-d21eab38a6a6.png)

**Comment by simonfrey** [comment]
Should be fixed with 3.2.7.5
