### ISSUE TITLE
Application reauthorizes when saving settings

### ISSUE THREAD

**Issue by abrain** [simonfrey/mastodon_wordpress_autopost#35]
Every time I hit the Save button in the plugin settings, the authorization flow with the Mastodon instance kicks off. This happens even though the plugin has been authorized before and can toot successfully. This also causes a new entry in your _Authorized Apps_ section in your Mastodon settings for every new authorization.

Plugin version 3.2.6

**Comment by simonfrey** [comment]
Thanks for your feedback here! It was in the end an easy fix (i hope). It will be rolled out with version 3.2.8
