### ISSUE TITLE
sizeof() warnings in PHP7.2

### ISSUE THREAD

**Issue by vasilisvg** [simonfrey/mastodon_wordpress_autopost#36]
When I post a blogpost without any tags I get a PHP warning.

> PHP message: PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in mastodon_autopost.php on line 487 …

There’s a simple solution that seems to work, but I guess it needs some extra testing:

Replace

```php
if (sizeof($post_tags) > 0) {
```

with 

```php
if ($post_tags) {
```

https://github.com/simonfrey/mastodon_wordpress_autopost/blob/69f33f1049b45d24ae89ef3800c4d134d1daa30e/autopost-to-mastodon/trunk/mastodon_autopost.php#L487

**Comment by simonfrey** [comment]
I tried it on my server with php 7.1 and it works as well. Will be added with 3.2.8

**Comment by edent** [comment]
I'm still getting these errors.

> PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in wp-content/plugins/autopost-to-mastodon/mastodon_autopost.php on line 545

https://github.com/simonfrey/mastodon_wordpress_autopost/blob/master/autopost-to-mastodon/trunk/mastodon_autopost.php#L545
