### ISSUE TITLE
Dropdown does not work on settings

### ISSUE THREAD

**Issue by arunsathiya** [simonfrey/mastodon_wordpress_autopost#39]
Clicking on the dropdown on the settings page does not seem to be responding.

<img width="439" alt="Screenshot 2019-05-02 at 10 02 40" src="https://user-images.githubusercontent.com/18581859/57056658-793c6580-6cc1-11e9-8f96-1acdcd546727.png">

However, when hovering over the input region of that field, a dropdown appears instantly. I believe it's expected to have the same behaviour on the dropdown, or that the dropdown responds on click.

**Comment by simonfrey** [comment]
Hey @arunsathiya, 
thanks for you feedback. I will close it as won't fix as it is a browser specific issue. I use the datalist element here. It is not implemented the same/completely in all browsers.(https://caniuse.com/#feat=datalist)
As long as the auto suggest works I am fine with it.
If it really bothers your, please consider a pull request. I will be happy to merge it.

Best,
Simon
