### ISSUE TITLE
wp_enqueue_script() with non-existing file

### ISSUE THREAD

**Issue by abrain** [simonfrey/mastodon_wordpress_autopost#42]
When creating or editing a post (or other type of content), the file `js/toot_editor.js` gets included. However, this file does not exist.
https://github.com/simonfrey/mastodon_wordpress_autopost/blob/91e931d36af8866c1c12d918a89eba018b1f3cd4/autopost-to-mastodon/trunk/mastodon_autopost.php#L119-L128

**Comment by simonfrey** [comment]
Thanks for that hint!
Removed that block with f7437a861d4b6e5d1c1763d2e1812819d0576e5f (Version 3.3.4)
