### ISSUE TITLE
marked as not updated/tested with current wordpress

### ISSUE THREAD

**Issue by harcesz** [simonfrey/mastodon_wordpress_autopost#53]
Bumping up the version on wordpress plugins might encourage more users, currently it looks abandoned, even tho fully functional. Thank you for this wonderful tool, a whole network of websites just got it! :D

**Comment by simonfrey** [comment]
Good idea. Done with https://github.com/simonfrey/mastodon_wordpress_autopost/commit/c24f4cef9582d676857690e1988551953afae713

If you like my work, please consider a [tip](https://simon-frey.com/tip)

**Comment by harcesz** [comment]
Currently poor AF but just dropped a polish translation to support the project :]
