### ISSUE TITLE
Mastodon Autopost : The given instance url belongs to no valid mastodon instance !

### ISSUE THREAD

**Issue by maxlinux2000** [simonfrey/mastodon_wordpress_autopost#55]
Hello
A few weeks ago I installed this plugin and it worked like a charm.
A couple of days ago it no longer worked because it did not send me the posts to my mastodon instance. So I have uninstalled it and reinstalled it.
Now when I insert the url of my session it tells me this:

"Mastodon Autopost: The given instance url belongs to no valid mastodon instance!"

What does it mean? I've looked at the wordpress error logs and they don't say anything.
Is it possible that my mastodon session is preventing me from entering? But how do I correct this?

my instance: https://social.tormentasolar.win/ 
below the software versions

![Captura de pantalla de 2021-03-10 19-31-41](https://user-images.githubusercontent.com/5683921/110679752-1dee2f00-81d8-11eb-8734-7042c371fa2a.png)
![Captura de pantalla de 2021-03-10 19-36-31](https://user-images.githubusercontent.com/5683921/110679782-25153d00-81d8-11eb-8d87-72239c6cb75e.png)

**Comment by simonfrey** [comment]
Hey @maxlinux2000,
thanks for reporting this bug. What are you typing into the instance field? 
I am asking this as it is important to only use the domain:
Correct: `social.tormentasolar.win`
Wrong: `https://social.tormentasolar.win/`

**Comment by maxlinux2000** [comment]
My mistake!
The error was in the DNS. The problem was that I have wordpress and mastodon inside the internal network together with a dns server that resolves the internal addresses.
Probably last week I made a modification and inadvertently I removed the record that indicated the internal address of mastodon. So wordpress got the external IP address and probably the firewall prevents the connection to the mastodon apis, therefore your plugin cannot work.

So you can close this bug.

just a note. In the address field you can put both "https://mastodon.social" and "mastodon.social". This works anyway

regards
and sorry for the trouble
