### ISSUE TITLE
unnecessary sizeOf() in mastodon_autopost.php fails on current PHP / Wordpress version

### ISSUE THREAD

**Issue by dummzeuch** [simonfrey/mastodon_wordpress_autopost#62]
in line 545 of mastodon_autopost.php the call to sizeOf is not necessary because forEach will work even if the array is empty. On contrast, sizeOf fails if the array is empty and will cause follow up errors.

The fix is to simply remove that check:

        $post_tags = get_the_tags($id);
        // <==== check was here
        if ($post_tags) {
            foreach ($post_tags as $tag) {
                $post_tags_content = $post_tags_content . '#' . preg_replace('/\s+/', '', html_entity_decode($tag->name, ENT_COMPAT, 'UTF-8')) . ' ';
            }
            $post_tags_content = trim($post_tags_content);
        }
        $message_template = str_replace("[tags]", $post_tags_content, $message_template);

**Comment by dummzeuch** [comment]
Apparently there is already a pull request for a fix
https://github.com/simonfrey/mastodon_wordpress_autopost/pull/58

**Comment by simonfrey** [comment]
Merged #58
